stages:
  - test
  - size_check
  - build
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - pytest tests/ -v --cov=src/xwe
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

lint:
  stage: test
  script:
    - flake8 src/ tests/
    - black --check src/ tests/
    - isort --check-only src/ tests/

e2e_playwright:
  stage: test
  image: mcr.microsoft.com/playwright/python:v1.53.1
  script:
    - pip install -r requirements.txt
    - npm ci
    - npx playwright install --with-deps
    - npx playwright test tests/e2e/character_reroll.spec.ts
  artifacts:
    when: always
    paths:
      - test-results/
      - playwright-report/

git_sizer:
  stage: size_check
  script:
    - git-sizer --critical --threshold=5242880

build:
  stage: build
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/
  only:
    - tags

deploy:
  stage: deploy
  script:
    - pip install twine
    - twine upload dist/*
  only:
    - tags
  when: manual
