repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      # - id: detect-aws-credentials   # ❌ 已注释掉
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-executables-have-shebangs

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort

  - repo: local
    hooks:
      - id: restructure-check
        name: Project structure check
        entry: scripts/run_structure_check.sh
        language: system
        files: ^xwe_v2/
