global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'xwe-monitor'

# Alertmanager 配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# 规则文件
rule_files:
  - "alerts.yml"

# 抓取配置
scrape_configs:
  # XianXia World Engine 应用
  - job_name: 'xwe'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:5000']
    metrics_path: '/metrics'

  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Grafana 监控
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
